<?xml version="1.0" ?>

<robot xmlns:xacro="https://www.ros.org/wiki/xacro" >
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="mu" value="0.98"/>
    <xacro:property name="mu2" value="0.98"/>
    <xacro:property name="jazzy_m" value="40" />
    <xacro:property name="wheel_m" value="0.5"/>
    <xacro:property name="wheel_r" value="0.075"/>
    <xacro:property name="wheel_l" value="0.0762"/>
    <xacro:property name="wheelbase" value="0.5" /> <!--base on the wheel diameter and chassis_x-->
    <xacro:property name="track" value="0.475" /> <!--base on the wheel width and chassis_y-->
    <xacro:property name="battery_m" value="40"/>
    <xacro:property name="bumper_x" value="0.04" />
    <xacro:property name="bumper_y" value="0.46" />
    <xacro:property name="bumper_z" value="0.125" />
    <xacro:property name="bumper_m" value="1" />

    <xacro:macro name="jazzy_base_macro">
      <link name="link_jazzy">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://ids_description/meshes/jazzy/base.obj" scale="0.1 0.1 0.1"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://ids_description/meshes/jazzy/base.obj" scale="0.1 0.1 0.1"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${jazzy_m}"/>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <inertia ixx="${jazzy_m*(0.4*0.4*0.15*0.15)}" ixy="0" ixz="0" iyy="${jazzy_m*(0.6*0.6*0.15*0.15)}" iyz="0" izz="${jazzy_m*(0.6*0.6*0.4*0.4)}"/>
        </inertial>
      </link>
      <!--bumper-->
      <joint name="joint_chassis_fbumper" type="fixed">
        <origin xyz="0.25 0 0.0375" rpy="0 0 0"/>
        <parent link="link_jazzy"/>
        <child link="link_fbumper"/>
      </joint>

      <link name="link_fbumper">
        <visual>
          <origin xyz="${bumper_x/2} 0 0" rpy="0 0 0" />
          <geometry>
            <box size="${bumper_x} ${bumper_y} ${bumper_z}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="${bumper_x/2} 0 0" rpy="0 0 0" />
          <geometry>
            <box size="${bumper_x} ${bumper_y} ${bumper_z}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${bumper_m}"/>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <inertia ixx="${(1/12)*bumper_m*(bumper_y*bumper_y+bumper_z*bumper_z)}" ixy="0" ixz="0" iyy="${(1/12)*bumper_m*(bumper_z*bumper_z+bumper_x*bumper_x)}" iyz="0" izz="${(1/12)*bumper_m*(bumper_x*bumper_x+bumper_y*bumper_y)}"/>
        </inertial>
      </link>
      <!--battery-->
      <joint name="joint_jazzy_battery" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="link_jazzy"/>
        <child link="link_battery"/>
      </joint>
      <link name="link_battery">
        <visual>
          <origin rpy="0 0 0" xyz="-0.1 0 0.4"/>
          <geometry>
            <box size="0.4 0.25 0.5"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="-0.1 0 0.25" />
          <geometry>
            <box size="0.4 0.25 0.5"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${battery_m}"/>
          <origin rpy="0 0 0" xyz="-0.1 0 0.25"/>
          <inertia ixx="${(1/12)*battery_m*(0.25*0.25+0.5*0.5)}" ixy="0" ixz="0" iyy="${(1/12)*battery_m*(0.4*0.4+0.5*0.5)}" iyz="0" izz="${(1/12)*battery_m*(0.4*0.4+0.25*0.25)}"/>
        </inertial>
      </link>
      <!--left rear wheel-->
      <joint name="joint_chassis_lrwheel" type="continuous">
        <origin xyz="${-wheelbase/2-0.125} ${track/2} 0" rpy="0 0 0" />
        <parent link="link_jazzy"/>
        <child link="link_lrwheel"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
      </joint>
      <link name="link_lrwheel">
        <visual>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
          <geometry>
            <cylinder length="${wheel_l}" radius="${wheel_r}"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0" />
          <geometry>
            <cylinder length="${wheel_l}" radius="${wheel_r}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${wheel_m}"/>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
          <inertia ixx="${(1/12)*wheel_m*(3*wheel_r*wheel_r+wheel_l*wheel_l)}" ixy="0" ixz="0" iyy="${(1/12)*wheel_m*(3*wheel_r*wheel_r+wheel_l*wheel_l)}" iyz="0" izz="${(1/2)*wheel_m*wheel_r*wheel_r}"/>
        </inertial>
      </link>

      <!--right rear wheel-->
      <joint name="joint_chassis_rrwheel" type="continuous">
        <origin xyz="${-wheelbase/2-0.125} -${track/2} 0" rpy="0 0 0" />
        <parent link="link_jazzy"/>
        <child link="link_rrwheel"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
      </joint>
      <link name="link_rrwheel">
        <visual>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
          <geometry>
            <cylinder length="${wheel_l}" radius="${wheel_r}"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0" />
          <geometry>
            <cylinder length="${wheel_l}" radius="${wheel_r}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${wheel_m}"/>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
          <inertia ixx="${(1/12)*wheel_m*(3*wheel_r*wheel_r+wheel_l*wheel_l)}" ixy="0" ixz="0" iyy="${(1/12)*wheel_m*(3*wheel_r*wheel_r+wheel_l*wheel_l)}" iyz="0" izz="${(1/2)*wheel_m*wheel_r*wheel_r}"/>
        </inertial>
      </link>

      <!--left front wheel-->
      <joint name="joint_chassis_lfwheel" type="continuous">
        <origin xyz="${wheelbase/2-0.125} ${track/2} 0" rpy="0 0 0" />
        <parent link="link_jazzy"/>
        <child link="link_lfwheel"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
      </joint>
      <link name="link_lfwheel">
        <visual>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
          <geometry>
            <cylinder length="${wheel_l}" radius="${wheel_r}"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0" />
          <geometry>
            <cylinder length="${wheel_l}" radius="${wheel_r}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${wheel_m}"/>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
          <inertia ixx="${(1/12)*wheel_m*(3*wheel_r*wheel_r+wheel_l*wheel_l)}" ixy="0" ixz="0" iyy="${(1/12)*wheel_m*(3*wheel_r*wheel_r+wheel_l*wheel_l)}" iyz="0" izz="${(1/2)*wheel_m*wheel_r*wheel_r}"/>
        </inertial>
      </link>

      <!--right front wheel-->
      <joint name="joint_chassis_rfwheel" type="continuous">
        <origin xyz="${wheelbase/2-0.125} -${track/2} 0" rpy="0 0 0" />
        <parent link="link_jazzy"/>
        <child link="link_rfwheel"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
      </joint>
      <link name="link_rfwheel">
        <visual>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
          <geometry>
            <cylinder length="${wheel_l}" radius="${wheel_r}"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0" />
          <geometry>
            <cylinder length="${wheel_l}" radius="${wheel_r}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${wheel_m}"/>
          <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
          <inertia ixx="${(1/12)*wheel_m*(3*wheel_r*wheel_r+wheel_l*wheel_l)}" ixy="0" ixz="0" iyy="${(1/12)*wheel_m*(3*wheel_r*wheel_r+wheel_l*wheel_l)}" iyz="0" izz="${(1/2)*wheel_m*wheel_r*wheel_r}"/>
        </inertial>
      </link>

      <gazebo>
        <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
          <updateRate>50.0</updateRate>
          <robotNamespace>$(arg ns)</robotNamespace>
          <leftFrontJoint>joint_chassis_lfwheel</leftFrontJoint>
          <rightFrontJoint>joint_chassis_rfwheel</rightFrontJoint>
          <leftRearJoint>joint_chassis_lrwheel</leftRearJoint>
          <rightRearJoint>joint_chassis_rrwheel</rightRearJoint>
          <wheelSeparation>${wheelbase}</wheelSeparation>
          <wheelDiameter>2*${wheel_r}</wheelDiameter>
          <torque>30</torque>
          <topicName>cmd_vel</topicName>
          <commandTopic>cmd_vel</commandTopic>
          <odometryTopic>odom</odometryTopic>
          <covariance_x>0.0001</covariance_x>
          <covariance_y>0.0001</covariance_y>
          <covariance_yaw>0.0001</covariance_yaw>
          <robotBaseFrame>link_chassis</robotBaseFrame>
          <odometryFrame>odom</odometryFrame>
          <broadcastTF>true</broadcastTF>
        </plugin>
      </gazebo>

      <gazebo reference="link_jazzy">
        <material>Gazebo/Grey</material>
      </gazebo>

      <gazebo reference="link_fbumper">
        <material>Gazebo/DarkGrey</material>
      </gazebo>

      <gazebo reference="link_lrwheel">
        <mu1>${mu}</mu1>
        <mu2>${mu2}</mu2>
        <material>Gazebo/Black</material>
      </gazebo>

      <gazebo reference="link_rrwheel">
        <mu1>${mu}</mu1>
        <mu2>${mu2}</mu2>
        <material>Gazebo/Black</material>
      </gazebo>

      <gazebo reference="link_lfwheel">
        <mu1>${mu}</mu1>
        <mu2>${mu2}</mu2>
        <material>Gazebo/Black</material>
      </gazebo>

      <gazebo reference="link_rfwheel">
        <mu1>${mu}</mu1>
        <mu2>${mu2}</mu2>
        <material>Gazebo/Black</material>
      </gazebo>
    </xacro:macro>
</robot>
