obstacle_range: 0.5
raytrace_range: 2.0
footprint: [[0.25, 0.25],[-0.25, 0.25],[-0.25, -0.25],[0.25,-0.25]] # counter-closkwise
#robot_radius: ir_of_robot
footprint_padding: 0.01

robot_base_frame: "link_chassis"

transform_tolerance: 0.1  # second delay
update_frequency: 5.0
publish_frequency: 2.0
resolution: 0.02
lethal_cost_threshold: 100

# layers
inflation:
  cost_scaling_factor: 10.0
  inflation_radius: 0.1

obstacles:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: link_hokuyo, data_type: LaserScan, topic: laser/scan, marking: true, clearing: true}
