global_costmap:
  global_frame: "map"
  static_map: true
  rolling_window: false # must be false if static_map is used
  footprint_padding: 0.02
  update_frequency: 5.0
  publish_frequency: 0.0
  plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}
